version: "3.9"

services:
  api:
    image: greenpearbear/skypro_docker_rdmitirev
    ports:
      - 80:80
    working_dir: /code
    volumes:
      - ./:/code/data
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: user_docker_pass
      POSTGRES_DB: docker_postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pg_data: