name: Build and deploy
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: action/checkout
      - name: docker build
        run: docker build -t greenpearbear/skypro_docker_rdmitirev:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push greenpearbear/skypro_docker_rdmitirev:$GITHUB_REF_NAME-$GITHUB_RUN_ID